// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CryptocurrenciesController from "./cryptocurrencies_controller"
application.register("cryptocurrencies", CryptocurrenciesController)

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)

import Users__UploadsController from "./users/uploads_controller"
application.register("users--uploads", Users__UploadsController)
