inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'config.ru'
    - 'Rakefile'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.eb'
    - 'config/**/*'
    - 'bin/*'
    - 'script/*'
    - 'vendor/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25