name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Tests & Security
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.6"
          bundler-cache: true

      - name: Add Linux platform to Gemfile.lock
        run: bundle lock --add-platform x86_64-linux

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run Brakeman
        run: bundle exec brakeman --exit-on-warn --no-progress --format json

      - name: Run RSpec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: bundle exec rspec

  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.6"
          bundler-cache: true

      - name: Add Linux platform to Gemfile.lock
        run: bundle lock --add-platform x86_64-linux

      - name: Run RuboCop (lint only)
        run: bundle exec rubocop --format github
